apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
    vgName: volumegroup1
    fsType: ext4
reclaimPolicy: Delete


# vgName: Necessary, vg should be created by hands with clouddisk type, and can be auto-create with localdisk type;

# pvType: (Optional) localdisk, clouddisk
#   clouddisk: default, not support auto create vg, and vg should pre-created by hands.
#   localdisk: support auto create vg using localdisks, and localdisks should be clean. And vgName is configured by "vgName";

# lvmType: (Optional) linear, striping
#   linear: default, generate linear type lvm volume;
#   striping: generate striping type lvm volume; only support localdisk now, and the striped number is the localdisk number;

# nodeAffinity: (Optional) true, false
#   true: default, provision pv with nodeAffinity configuration;
#   false: provision pv without nodeAffinity configuration;