apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm-striping
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
    vgName: volumegroup1
    fsType: ext4
    pvType: localdisk
    lvmType: striping
reclaimPolicy: Delete