apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpfs-csi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cpfsplugin.csi.alibabacloud.com
    volumeHandle: cpfs-csi-pv
    volumeAttributes:
      server: "192.168.1.240@tcp:192.168.1.241@tcp"
      fileSystem: "09447c85"
      subPath: "/k8s"