kind: Service
apiVersion: v1
metadata:
  name: csi-cpfs-provisioner
  namespace: kube-system
  labels:
    app: csi-cpfs-provisioner
spec:
  selector:
    app: csi-cpfs-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-cpfs-provisioner
  namespace: kube-system
spec:
  serviceName: "csi-cpfs-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cpfs-provisioner
    spec:
      tolerations:
      - operator: "Exists"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: admin
      hostNetwork: true
      containers:
        - name: csi-nas-external-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-provisioner:v1.2.0
          args:
            - "--provisioner=cpfsplugin.csi.alibabacloud.com"
            - "--csi-address=$(ADDRESS)"
            - "--volume-name-prefix=cpfs"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /socketDir/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /socketDir
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/cpfsplugin.csi.alibabacloud.com
            type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate