version: "2"
issues:
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false
linters:
  settings:
    staticcheck:
      checks: [
        "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", # staticcheck defaults
        "-QF1008", # Omit embedded fields from selector expression
      ]
