coverage:
  paths:
    - coverage.out

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
  acceptable: 80% # fail if diff (incremental) coverage < 80%

summary:
  if: true

report:
  if: is_pull_request
  datastores:
    - artifact://${GITHUB_REPOSITORY}
