apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: alicloud-disk-ssd-beijing-b
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    zoneId: cn-beijing-b
    regionId: cn-beijing
    type: cloud_ssd
    diskTags: "team:dev,user:david"
reclaimPolicy: Retain

# diskTags to add tags when create disk.
# tags use "," to division, and tag format as "key:value";