kind: Service
apiVersion: v1
metadata:
  name: csi-attacher
  labels:
    app: csi-attacher
spec:
  selector:
    app: csi-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-attacher
spec:
  serviceName: "csi-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      nodeSelector:
         node-role.kubernetes.io/master: ""
      serviceAccount: alicloud-csi-plugin
      containers:
        - name: csi-diskattacher
          image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-attacher:v1.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /socketDir/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: disk-socket-dir
              mountPath: /socketDir
        - name: csi-nasattacher
          image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-attacher:v1.0.0
          args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
          env:
          - name: ADDRESS
            value: /socketDir/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
          - name: nas-socket-dir
            mountPath: /socketDir
        - name: csi-ossattacher
          image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-attacher:v1.0.0
          args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
          env:
          - name: ADDRESS
            value: /socketDir/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
          - name: oss-socket-dir
            mountPath: /socketDir
      volumes:
        - name: disk-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/diskplugin.csi.alibabacloud.com
            type: DirectoryOrCreate
        - name: nas-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/nasplugin.csi.alibabacloud.com
            type: DirectoryOrCreate
        - name: oss-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/ossplugin.csi.alibabacloud.com
            type: DirectoryOrCreate