// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/bmcpfs/internal/fileset.go

// Package internal is a generated GoMock package.
package internal

import (
	"reflect"

	client "github.com/alibabacloud-go/nas-20170626/v4/client"
	gomock "github.com/golang/mock/gomock"
)

// GoMockNasClient is a mock of NasClient interface.
type GoMockNasClient struct {
	ctrl     *gomock.Controller
	recorder *GoMockNasClientMockRecorder
}

// GoMockNasClientMockRecorder is the mock recorder for GoMockNasClient.
type GoMockNasClientMockRecorder struct {
	mock *GoMockNasClient
}

// NewGoMockNasClient creates a new mock instance.
func NewGoMockNasClient(ctrl *gomock.Controller) *GoMockNasClient {
	mock := &GoMockNasClient{ctrl: ctrl}
	mock.recorder = &GoMockNasClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockNasClient) EXPECT() *GoMockNasClientMockRecorder {
	return m.recorder
}

// CreateFileset mocks base method.
func (m *GoMockNasClient) CreateFileset(request *client.CreateFilesetRequest) (*client.CreateFilesetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileset", request)
	ret0, _ := ret[0].(*client.CreateFilesetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFileset indicates an expected call of CreateFileset.
func (mr *GoMockNasClientMockRecorder) CreateFileset(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileset", reflect.TypeOf((*GoMockNasClient)(nil).CreateFileset), request)
}

// DeleteFileset mocks base method.
func (m *GoMockNasClient) DeleteFileset(request *client.DeleteFilesetRequest) (*client.DeleteFilesetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileset", request)
	ret0, _ := ret[0].(*client.DeleteFilesetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFileset indicates an expected call of DeleteFileset.
func (mr *GoMockNasClientMockRecorder) DeleteFileset(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileset", reflect.TypeOf((*GoMockNasClient)(nil).DeleteFileset), request)
}

// DescribeFilesets mocks base method.
func (m *GoMockNasClient) DescribeFilesets(request *client.DescribeFilesetsRequest) (*client.DescribeFilesetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFilesets", request)
	ret0, _ := ret[0].(*client.DescribeFilesetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFilesets indicates an expected call of DescribeFilesets.
func (mr *GoMockNasClientMockRecorder) DescribeFilesets(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFilesets", reflect.TypeOf((*GoMockNasClient)(nil).DescribeFilesets), request)
}
