apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: alicloud-lvm-expand
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
    vgName: vgtest
    fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true