apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: csi-pmem-lvm
provisioner: localplugin.csi.alibabacloud.com
parameters:
    volumeType: PMEM
    pmemType: "lvm"
    fsType: ext4
    lvmType: "striping"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

# volumeType: support LVM/MountPoint/Device/PMEM types

# pmemType: support lvm/direct types;
# default as lvm;
# direct: means not create volumegroup and use region create namespace

# lvmType: (Optional) linear, striping
#   linear: default, generate linear type lvm volume;
#   striping: generate striping type lvm volume; only support localdisk now, and the striped number is the localdisk number;

# nodeAffinity: (Optional) true, false
#   true: default, provision pv with nodeAffinity configuration;
#   false: provision pv without nodeAffinity configuration;
