apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: csi-pmem-lvm
provisioner: localplugin.csi.alibabacloud.com
parameters:
    volumeType: PMEM
    pmemType: "direct"
    fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

# volumeType: support LVM/MountPoint/Device/PMEM types

# pmemType: support lvm/direct types;
# default as lvm;
# direct: means not create volumegroup and use region create namespace

# nodeAffinity: (Optional) true, false
#   true: default, provision pv with nodeAffinity configuration;
#   false: provision pv without nodeAffinity configuration;
