apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-fs
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  # volumeAs is optional, should be 'filesystem' or 'subpath', default value is 'subpath'
  volumeAs: filesystem
  fileSystemType: standard
  # storageType is optional, should be 'Performance' or 'Capacity', default value is 'Performance'
  storageType: Performance
  regionId: cn-hangzhou
  # zoneId is optional, default value is the kubernetes cluster's worker's zoneId
  zoneId: cn-hangzhou-f
  # vpcId is required
  vpcId: "vpc-xxxxxxxx"
  # vSwitchId is required
  vSwitchId: "vsw-xxxxxxxx"
  # accessGroupName is optional, default value is 'DEFAULT_VPC_GROUP_NAME'
  accessGroupName: "DEFAULT_VPC_GROUP_NAME"
  # deleteVolume is optional, should be 'true' or 'false', default value is 'false'
  deleteVolume: "false"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
