package local

const (
	LOCAL_GRPC_PROVISION                 = "LOCAL_GRPC_PROVISION"
	LOCAL_HOSTNAME_AS_TOPO               = "LOCAL_HOSTNAME_AS_TOPO"
	LOCAL_TOPO_KEY_DEFINED               = "LOCAL_TOPO_KEY_DEFINED"
	CAPACITY_TO_NODE                     = "CAPACITY_TO_NODE"
	LOCAL_SPARSE_TEMPLATE_FILEDIR        = "LOCAL_SPARSE_TEMPLATE_FILEDIR"
	LOCAL_SPARSE_TEMPLATE_SIZE           = "LOCAL_SPARSE_TEMPLATE_SIZE"
	LOCAL_SPARSE_TOTAL_AVAILABLE_GI      = "LOCAL_SPARSE_TOTAL_AVAILABLE_GI"
	LOCAL_SPARSE_TOTAL_AVAILABLE_PERCENT = "LOCAL_SPARSE_TOTAL_AVAILABLE_PERCENT"
)
