apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-disk
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    zoneId: cn-hangzhou-b
    regionId: cn-hangzhou
    fsType: ext4
    type: san_ssd
    readOnly: "false"
reclaimPolicy: Delete