apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-prod-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: juicefs-prod-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-dev-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: juicefs-dev-pv
  storageClassName: ""
