apiVersion: v1
kind: Secret
metadata:
  name: juicefs-configmap-creds
  namespace: default
type: Opaque
stringData:
  accessKeyId: "<your-access-key-id>"
  accessKeySecret: "<your-access-key-secret>"
