apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-advanced-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: juicefs-advanced-pv
  storageClassName: ""
