apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-disk
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    fsType: ext4
    type: cloud_ssd
    readOnly: "false"
    resourceGroupId: rg-aekzpe7mpvj7r6y
reclaimPolicy: Delete