apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-dbfs-config
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      alicloud-pvname: csi-dbfs-config