apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-dbfs-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-dbfs-ssd-zhangjiakou-a