apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:v1.7.9
        volumeMounts:
        - name: csi-dbfs-data
          mountPath: /data
        - name: csi-dbfs-config
            mountPath: /config
      volumes:
        - name: csi-dbfs-data
          persistentVolumeClaim:
            claimName: csi-dbfs-data
        - name: csi-dbfs-config
            persistentVolumeClaim:
              claimName: csi-dbfs-config