package disk

import (
	"encoding/json"
	log "github.com/sirupsen/logrus"
)

// DiskTypeMatchMap disk and ecs type
var DiskTypeMatchMap = map[string]string{}

func init() {
	err := json.Unmarshal([]byte(diskMatchMapStr), &DiskTypeMatchMap)
	if err != nil {
		log.Infof("DiskMatchMap Init: cannot Unmarshal disk type match with error: %s", err.Error())
	}
}

var diskMatchMapStr = `{
  "ecs.g7se": "cloud_essd",
  "ecs.g7a": "cloud_essd",
  "ecs.g7": "cloud_essd",
  "ecs.g7t": "cloud_essd",
  "ecs.g7ne": "cloud_essd",
  "ecs.g6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.g6a": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.g6t": "cloud_essd",
  "ecs.g6e": "cloud_essd",
  "ecs.g5": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.g5ne": "cloud_efficiency,cloud_ssd",
  "ecs.c7re": "cloud_essd",
  "ecs.c7se": "cloud_essd",
  "ecs.c7a": "cloud_essd",
  "ecs.c7": "cloud_essd",
  "ecs.c7t": "cloud_essd",
  "ecs.c6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.c6a": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.c6t": "cloud_essd",
  "ecs.c6e": "cloud_essd",
  "ecs.c5": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ic5": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.re7p": "cloud_essd",
  "ecs.r7p": "cloud_essd",
  "ecs.r7se": "cloud_essd",
  "ecs.r7a": "cloud_essd",
  "ecs.r7": "cloud_essd",
  "ecs.r7t": "cloud_essd",
  "ecs.r6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.re6p": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.r6a": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.r6e": "cloud_essd",
  "ecs.re6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.r5": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.d3c": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.d2c": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.d2s": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.d1ne": "cloud_efficiency,cloud_ssd",
  "ecs.i4p": "cloud_essd",
  "ecs.i3g": "cloud_essd",
  "ecs.i3": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.i2": "cloud_efficiency,cloud_ssd",
  "ecs.i2g": "cloud_efficiency,cloud_ssd",
  "ecs.i2ne": "cloud_efficiency,cloud_ssd",
  "ecs.i2gne": "cloud_efficiency,cloud_ssd",
  "ecs.hfc7": "cloud_essd",
  "ecs.hfc6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.hfg7": "cloud_essd",
  "ecs.hfg6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.hfr7": "cloud_essd",
  "ecs.hfr6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.sn2ne": "cloud_efficiency,cloud_ssd",
  "ecs.sn1ne": "cloud_efficiency,cloud_ssd",
  "ecs.re4": "cloud_efficiency,cloud_ssd",
  "ecs.re4e": "cloud_efficiency,cloud_ssd",
  "ecs.se1ne": "cloud_efficiency,cloud_ssd",
  "ecs.se1": "cloud_efficiency,cloud_ssd",
  "ecs.d1": "cloud_efficiency,cloud_ssd",
  "ecs.i1": "cloud_efficiency,cloud_ssd",
  "ecs.hfc5": "cloud_efficiency,cloud_ssd",
  "ecs.hfg5": "cloud_efficiency,cloud_ssd",
  "ecs.g8m": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.g6r": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.c6r": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.sgn7i-vws": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.vgn7i-vws": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.gn7e": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.gn7i": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.gn7": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.vgn6i": "cloud_efficiency,cloud_ssd",
  "ecs.gn6i": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.gn6e": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.gn6v": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.video-enhance": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.video-trans": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.f3": "cloud_efficiency,cloud_ssd",
  "ecs.ebman1": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmgi6s": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.vgn5i": "cloud_efficiency,cloud_ssd",
  "ecs.gn5": "cloud_efficiency,cloud_ssd",
  "ecs.gn5i": "cloud_efficiency,cloud_ssd",
  "ecs.f1": "cloud_efficiency,cloud_ssd",
  "ecs.ebmgn7e": "cloud_essd",
  "ecs.ebmgn7i": "cloud_efficiency,cloud_ssd",
  "ecs.ebmgn7": "cloud_efficiency,cloud_ssd",
  "ecs.ebmgn6ia": "cloud_essd",
  "ecs.ebmgn6e": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmgn6v": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmgn6i": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmc7": "cloud_essd",
  "ecs.ebmc7a": "cloud_essd",
  "ecs.ebmc6me": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmc6a": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmc6e": "cloud_essd",
  "ecs.ebmc6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmg7": "cloud_essd",
  "ecs.ebmg7a": "cloud_essd",
  "ecs.ebmg6a": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmg6e": "cloud_essd",
  "ecs.ebmg6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmr7": "cloud_essd",
  "ecs.ebmr7a": "cloud_essd",
  "ecs.ebmr6a": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmr6e": "cloud_essd",
  "ecs.ebmr6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmre6p": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmre6-6t": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmhfg7": "cloud_essd",
  "ecs.ebmhfc7": "cloud_essd",
  "ecs.ebmhfr7": "cloud_essd",
  "ecs.ebmhfg6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmhfc6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmhfr6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmi2g": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.sccg7": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.sccc7": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.scchfc6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.scchfg6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.scchfr6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.scch5": "cloud_efficiency,cloud_ssd",
  "ecs.sccg5": "cloud_efficiency,cloud_ssd",
  "ecs.sccgn6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.sccgn7ex": "cloud_essd",
  "ecs.sccgn6e": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmc5s": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmg5s": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmr5s": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.ebmg5": "cloud_efficiency,cloud_ssd",
  "ecs.ebmc4": "cloud_efficiency,cloud_ssd",
  "ecs.t6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.t5": "cloud_efficiency,cloud_ssd",
  "ecs.s6": "cloud_efficiency,cloud_ssd,cloud_essd",
  "ecs.v5": "cloud_efficiency,cloud_ssd,cloud_essd"
}`
