apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
spec:
  snapshotClassName: default-snapclass
  source:
    name: disk-pvc
    kind: PersistentVolumeClaim
