apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
    vgName: volumegroup1
    fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

# the parameters same as common storageclass