// Code generated by MockGen. DO NOT EDIT.
// Source: nas_v2_interface.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	reflect "reflect"

	client "github.com/alibabacloud-go/nas-20170626/v3/client"
	gomock "github.com/golang/mock/gomock"
)

// MockNasV2Interface is a mock of NasV2Interface interface.
type MockNasV2Interface struct {
	ctrl     *gomock.Controller
	recorder *MockNasV2InterfaceMockRecorder
}

// MockNasV2InterfaceMockRecorder is the mock recorder for MockNasV2Interface.
type MockNasV2InterfaceMockRecorder struct {
	mock *MockNasV2Interface
}

// NewMockNasV2Interface creates a new mock instance.
func NewMockNasV2Interface(ctrl *gomock.Controller) *MockNasV2Interface {
	mock := &MockNasV2Interface{ctrl: ctrl}
	mock.recorder = &MockNasV2InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNasV2Interface) EXPECT() *MockNasV2InterfaceMockRecorder {
	return m.recorder
}

// CancelDirQuota mocks base method.
func (m *MockNasV2Interface) CancelDirQuota(request *client.CancelDirQuotaRequest) (*client.CancelDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelDirQuota", request)
	ret0, _ := ret[0].(*client.CancelDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelDirQuota indicates an expected call of CancelDirQuota.
func (mr *MockNasV2InterfaceMockRecorder) CancelDirQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelDirQuota", reflect.TypeOf((*MockNasV2Interface)(nil).CancelDirQuota), request)
}

// CreateAccessPoint mocks base method.
func (m *MockNasV2Interface) CreateAccessPoint(request *client.CreateAccessPointRequest) (*client.CreateAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPoint", request)
	ret0, _ := ret[0].(*client.CreateAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPoint indicates an expected call of CreateAccessPoint.
func (mr *MockNasV2InterfaceMockRecorder) CreateAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPoint", reflect.TypeOf((*MockNasV2Interface)(nil).CreateAccessPoint), request)
}

// CreateDir mocks base method.
func (m *MockNasV2Interface) CreateDir(request *client.CreateDirRequest) (*client.CreateDirResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDir", request)
	ret0, _ := ret[0].(*client.CreateDirResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDir indicates an expected call of CreateDir.
func (mr *MockNasV2InterfaceMockRecorder) CreateDir(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDir", reflect.TypeOf((*MockNasV2Interface)(nil).CreateDir), request)
}

// DeleteAccessPoint mocks base method.
func (m *MockNasV2Interface) DeleteAccessPoint(request *client.DeleteAccessPointRequest) (*client.DeleteAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPoint", request)
	ret0, _ := ret[0].(*client.DeleteAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessPoint indicates an expected call of DeleteAccessPoint.
func (mr *MockNasV2InterfaceMockRecorder) DeleteAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPoint", reflect.TypeOf((*MockNasV2Interface)(nil).DeleteAccessPoint), request)
}

// DescribeAccessPoint mocks base method.
func (m *MockNasV2Interface) DescribeAccessPoint(request *client.DescribeAccessPointRequest) (*client.DescribeAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAccessPoint", request)
	ret0, _ := ret[0].(*client.DescribeAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAccessPoint indicates an expected call of DescribeAccessPoint.
func (mr *MockNasV2InterfaceMockRecorder) DescribeAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAccessPoint", reflect.TypeOf((*MockNasV2Interface)(nil).DescribeAccessPoint), request)
}

// DescribeFileSystems mocks base method.
func (m *MockNasV2Interface) DescribeFileSystems(request *client.DescribeFileSystemsRequest) (*client.DescribeFileSystemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFileSystems", request)
	ret0, _ := ret[0].(*client.DescribeFileSystemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFileSystems indicates an expected call of DescribeFileSystems.
func (mr *MockNasV2InterfaceMockRecorder) DescribeFileSystems(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFileSystems", reflect.TypeOf((*MockNasV2Interface)(nil).DescribeFileSystems), request)
}

// GetRecycleBinAttribute mocks base method.
func (m *MockNasV2Interface) GetRecycleBinAttribute(request *client.GetRecycleBinAttributeRequest) (*client.GetRecycleBinAttributeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecycleBinAttribute", request)
	ret0, _ := ret[0].(*client.GetRecycleBinAttributeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecycleBinAttribute indicates an expected call of GetRecycleBinAttribute.
func (mr *MockNasV2InterfaceMockRecorder) GetRecycleBinAttribute(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecycleBinAttribute", reflect.TypeOf((*MockNasV2Interface)(nil).GetRecycleBinAttribute), request)
}

// SetDirQuota mocks base method.
func (m *MockNasV2Interface) SetDirQuota(request *client.SetDirQuotaRequest) (*client.SetDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDirQuota", request)
	ret0, _ := ret[0].(*client.SetDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDirQuota indicates an expected call of SetDirQuota.
func (mr *MockNasV2InterfaceMockRecorder) SetDirQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDirQuota", reflect.TypeOf((*MockNasV2Interface)(nil).SetDirQuota), request)
}
