// Code generated by MockGen. DO NOT EDIT.
// Source: nas_interface.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	reflect "reflect"

	client "github.com/alibabacloud-go/nas-20170626/v3/client"
	gomock "github.com/golang/mock/gomock"
)

// MockNasInterface is a mock of NasInterface interface.
type MockNasInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNasInterfaceMockRecorder
}

// MockNasInterfaceMockRecorder is the mock recorder for MockNasInterface.
type MockNasInterfaceMockRecorder struct {
	mock *MockNasInterface
}

// NewMockNasInterface creates a new mock instance.
func NewMockNasInterface(ctrl *gomock.Controller) *MockNasInterface {
	mock := &MockNasInterface{ctrl: ctrl}
	mock.recorder = &MockNasInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNasInterface) EXPECT() *MockNasInterfaceMockRecorder {
	return m.recorder
}

// CancelDirQuota mocks base method.
func (m *MockNasInterface) CancelDirQuota(request *client.CancelDirQuotaRequest) (*client.CancelDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelDirQuota", request)
	ret0, _ := ret[0].(*client.CancelDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelDirQuota indicates an expected call of CancelDirQuota.
func (mr *MockNasInterfaceMockRecorder) CancelDirQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelDirQuota", reflect.TypeOf((*MockNasInterface)(nil).CancelDirQuota), request)
}

// CreateAccessPoint mocks base method.
func (m *MockNasInterface) CreateAccessPoint(request *client.CreateAccessPointRequest) (*client.CreateAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPoint", request)
	ret0, _ := ret[0].(*client.CreateAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPoint indicates an expected call of CreateAccessPoint.
func (mr *MockNasInterfaceMockRecorder) CreateAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPoint", reflect.TypeOf((*MockNasInterface)(nil).CreateAccessPoint), request)
}

// CreateDir mocks base method.
func (m *MockNasInterface) CreateDir(request *client.CreateDirRequest) (*client.CreateDirResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDir", request)
	ret0, _ := ret[0].(*client.CreateDirResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDir indicates an expected call of CreateDir.
func (mr *MockNasInterfaceMockRecorder) CreateDir(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDir", reflect.TypeOf((*MockNasInterface)(nil).CreateDir), request)
}

// DeleteAccessPoint mocks base method.
func (m *MockNasInterface) DeleteAccessPoint(request *client.DeleteAccessPointRequest) (*client.DeleteAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPoint", request)
	ret0, _ := ret[0].(*client.DeleteAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessPoint indicates an expected call of DeleteAccessPoint.
func (mr *MockNasInterfaceMockRecorder) DeleteAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPoint", reflect.TypeOf((*MockNasInterface)(nil).DeleteAccessPoint), request)
}

// DescribeAccessPoint mocks base method.
func (m *MockNasInterface) DescribeAccessPoint(request *client.DescribeAccessPointRequest) (*client.DescribeAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAccessPoint", request)
	ret0, _ := ret[0].(*client.DescribeAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAccessPoint indicates an expected call of DescribeAccessPoint.
func (mr *MockNasInterfaceMockRecorder) DescribeAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAccessPoint", reflect.TypeOf((*MockNasInterface)(nil).DescribeAccessPoint), request)
}

// GetRecycleBinAttribute mocks base method.
func (m *MockNasInterface) GetRecycleBinAttribute(request *client.GetRecycleBinAttributeRequest) (*client.GetRecycleBinAttributeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecycleBinAttribute", request)
	ret0, _ := ret[0].(*client.GetRecycleBinAttributeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecycleBinAttribute indicates an expected call of GetRecycleBinAttribute.
func (mr *MockNasInterfaceMockRecorder) GetRecycleBinAttribute(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecycleBinAttribute", reflect.TypeOf((*MockNasInterface)(nil).GetRecycleBinAttribute), request)
}

// SetDirQuota mocks base method.
func (m *MockNasInterface) SetDirQuota(request *client.SetDirQuotaRequest) (*client.SetDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDirQuota", request)
	ret0, _ := ret[0].(*client.SetDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDirQuota indicates an expected call of SetDirQuota.
func (mr *MockNasInterfaceMockRecorder) SetDirQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDirQuota", reflect.TypeOf((*MockNasInterface)(nil).SetDirQuota), request)
}
