// Code generated by MockGen. DO NOT EDIT.
// Source: nas_v1_interface.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	reflect "reflect"

	nas "github.com/aliyun/alibaba-cloud-sdk-go/services/nas"
	gomock "github.com/golang/mock/gomock"
)

// MockNasV1Interface is a mock of NasV1Interface interface.
type MockNasV1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockNasV1InterfaceMockRecorder
}

// MockNasV1InterfaceMockRecorder is the mock recorder for MockNasV1Interface.
type MockNasV1InterfaceMockRecorder struct {
	mock *MockNasV1Interface
}

// NewMockNasV1Interface creates a new mock instance.
func NewMockNasV1Interface(ctrl *gomock.Controller) *MockNasV1Interface {
	mock := &MockNasV1Interface{ctrl: ctrl}
	mock.recorder = &MockNasV1InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNasV1Interface) EXPECT() *MockNasV1InterfaceMockRecorder {
	return m.recorder
}

// CreateFileSystem mocks base method.
func (m *MockNasV1Interface) CreateFileSystem(request *nas.CreateFileSystemRequest) (*nas.CreateFileSystemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileSystem", request)
	ret0, _ := ret[0].(*nas.CreateFileSystemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFileSystem indicates an expected call of CreateFileSystem.
func (mr *MockNasV1InterfaceMockRecorder) CreateFileSystem(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileSystem", reflect.TypeOf((*MockNasV1Interface)(nil).CreateFileSystem), request)
}

// CreateMountTarget mocks base method.
func (m *MockNasV1Interface) CreateMountTarget(request *nas.CreateMountTargetRequest) (*nas.CreateMountTargetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMountTarget", request)
	ret0, _ := ret[0].(*nas.CreateMountTargetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMountTarget indicates an expected call of CreateMountTarget.
func (mr *MockNasV1InterfaceMockRecorder) CreateMountTarget(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMountTarget", reflect.TypeOf((*MockNasV1Interface)(nil).CreateMountTarget), request)
}

// DeleteFileSystem mocks base method.
func (m *MockNasV1Interface) DeleteFileSystem(request *nas.DeleteFileSystemRequest) (*nas.DeleteFileSystemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileSystem", request)
	ret0, _ := ret[0].(*nas.DeleteFileSystemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFileSystem indicates an expected call of DeleteFileSystem.
func (mr *MockNasV1InterfaceMockRecorder) DeleteFileSystem(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileSystem", reflect.TypeOf((*MockNasV1Interface)(nil).DeleteFileSystem), request)
}

// DeleteMountTarget mocks base method.
func (m *MockNasV1Interface) DeleteMountTarget(request *nas.DeleteMountTargetRequest) (*nas.DeleteMountTargetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMountTarget", request)
	ret0, _ := ret[0].(*nas.DeleteMountTargetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMountTarget indicates an expected call of DeleteMountTarget.
func (mr *MockNasV1InterfaceMockRecorder) DeleteMountTarget(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMountTarget", reflect.TypeOf((*MockNasV1Interface)(nil).DeleteMountTarget), request)
}

// DescribeFileSystems mocks base method.
func (m *MockNasV1Interface) DescribeFileSystems(request *nas.DescribeFileSystemsRequest) (*nas.DescribeFileSystemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFileSystems", request)
	ret0, _ := ret[0].(*nas.DescribeFileSystemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFileSystems indicates an expected call of DescribeFileSystems.
func (mr *MockNasV1InterfaceMockRecorder) DescribeFileSystems(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFileSystems", reflect.TypeOf((*MockNasV1Interface)(nil).DescribeFileSystems), request)
}

// DescribeMountTargets mocks base method.
func (m *MockNasV1Interface) DescribeMountTargets(request *nas.DescribeMountTargetsRequest) (*nas.DescribeMountTargetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeMountTargets", request)
	ret0, _ := ret[0].(*nas.DescribeMountTargetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeMountTargets indicates an expected call of DescribeMountTargets.
func (mr *MockNasV1InterfaceMockRecorder) DescribeMountTargets(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeMountTargets", reflect.TypeOf((*MockNasV1Interface)(nil).DescribeMountTargets), request)
}

// TagResources mocks base method.
func (m *MockNasV1Interface) TagResources(request *nas.TagResourcesRequest) (*nas.TagResourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagResources", request)
	ret0, _ := ret[0].(*nas.TagResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagResources indicates an expected call of TagResources.
func (mr *MockNasV1InterfaceMockRecorder) TagResources(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResources", reflect.TypeOf((*MockNasV1Interface)(nil).TagResources), request)
}
