// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/ecsinterface.go

// Package cloud is a generated GoMock package.
package cloud

import (
	context "context"
	reflect "reflect"

	client "github.com/alibabacloud-go/ecs-20140526/v7/client"
	dara "github.com/alibabacloud-go/tea/dara"
	ecs "github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"
	gomock "github.com/golang/mock/gomock"
)

// MockECSInterface is a mock of ECSInterface interface.
type MockECSInterface struct {
	ctrl     *gomock.Controller
	recorder *MockECSInterfaceMockRecorder
}

// MockECSInterfaceMockRecorder is the mock recorder for MockECSInterface.
type MockECSInterfaceMockRecorder struct {
	mock *MockECSInterface
}

// NewMockECSInterface creates a new mock instance.
func NewMockECSInterface(ctrl *gomock.Controller) *MockECSInterface {
	mock := &MockECSInterface{ctrl: ctrl}
	mock.recorder = &MockECSInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockECSInterface) EXPECT() *MockECSInterfaceMockRecorder {
	return m.recorder
}

// AttachDisk mocks base method.
func (m *MockECSInterface) AttachDisk(request *ecs.AttachDiskRequest) (*ecs.AttachDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachDisk", request)
	ret0, _ := ret[0].(*ecs.AttachDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachDisk indicates an expected call of AttachDisk.
func (mr *MockECSInterfaceMockRecorder) AttachDisk(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachDisk", reflect.TypeOf((*MockECSInterface)(nil).AttachDisk), request)
}

// CreateDisk mocks base method.
func (m *MockECSInterface) CreateDisk(request *ecs.CreateDiskRequest) (*ecs.CreateDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDisk", request)
	ret0, _ := ret[0].(*ecs.CreateDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDisk indicates an expected call of CreateDisk.
func (mr *MockECSInterfaceMockRecorder) CreateDisk(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDisk", reflect.TypeOf((*MockECSInterface)(nil).CreateDisk), request)
}

// CreateSnapshot mocks base method.
func (m *MockECSInterface) CreateSnapshot(request *ecs.CreateSnapshotRequest) (*ecs.CreateSnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", request)
	ret0, _ := ret[0].(*ecs.CreateSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockECSInterfaceMockRecorder) CreateSnapshot(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockECSInterface)(nil).CreateSnapshot), request)
}

// DeleteDisk mocks base method.
func (m *MockECSInterface) DeleteDisk(request *ecs.DeleteDiskRequest) (*ecs.DeleteDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDisk", request)
	ret0, _ := ret[0].(*ecs.DeleteDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDisk indicates an expected call of DeleteDisk.
func (mr *MockECSInterfaceMockRecorder) DeleteDisk(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDisk", reflect.TypeOf((*MockECSInterface)(nil).DeleteDisk), request)
}

// DescribeAvailableResource mocks base method.
func (m *MockECSInterface) DescribeAvailableResource(request *ecs.DescribeAvailableResourceRequest) (*ecs.DescribeAvailableResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAvailableResource", request)
	ret0, _ := ret[0].(*ecs.DescribeAvailableResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAvailableResource indicates an expected call of DescribeAvailableResource.
func (mr *MockECSInterfaceMockRecorder) DescribeAvailableResource(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAvailableResource", reflect.TypeOf((*MockECSInterface)(nil).DescribeAvailableResource), request)
}

// DescribeDisks mocks base method.
func (m *MockECSInterface) DescribeDisks(request *ecs.DescribeDisksRequest) (*ecs.DescribeDisksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDisks", request)
	ret0, _ := ret[0].(*ecs.DescribeDisksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDisks indicates an expected call of DescribeDisks.
func (mr *MockECSInterfaceMockRecorder) DescribeDisks(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDisks", reflect.TypeOf((*MockECSInterface)(nil).DescribeDisks), request)
}

// DescribeInstanceHistoryEvents mocks base method.
func (m *MockECSInterface) DescribeInstanceHistoryEvents(request *ecs.DescribeInstanceHistoryEventsRequest) (*ecs.DescribeInstanceHistoryEventsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeInstanceHistoryEvents", request)
	ret0, _ := ret[0].(*ecs.DescribeInstanceHistoryEventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstanceHistoryEvents indicates an expected call of DescribeInstanceHistoryEvents.
func (mr *MockECSInterfaceMockRecorder) DescribeInstanceHistoryEvents(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstanceHistoryEvents", reflect.TypeOf((*MockECSInterface)(nil).DescribeInstanceHistoryEvents), request)
}

// DescribeInstances mocks base method.
func (m *MockECSInterface) DescribeInstances(request *ecs.DescribeInstancesRequest) (*ecs.DescribeInstancesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeInstances", request)
	ret0, _ := ret[0].(*ecs.DescribeInstancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstances indicates an expected call of DescribeInstances.
func (mr *MockECSInterfaceMockRecorder) DescribeInstances(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstances", reflect.TypeOf((*MockECSInterface)(nil).DescribeInstances), request)
}

// DescribeSnapshots mocks base method.
func (m *MockECSInterface) DescribeSnapshots(request *ecs.DescribeSnapshotsRequest) (*ecs.DescribeSnapshotsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeSnapshots", request)
	ret0, _ := ret[0].(*ecs.DescribeSnapshotsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeSnapshots indicates an expected call of DescribeSnapshots.
func (mr *MockECSInterfaceMockRecorder) DescribeSnapshots(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSnapshots", reflect.TypeOf((*MockECSInterface)(nil).DescribeSnapshots), request)
}

// DetachDisk mocks base method.
func (m *MockECSInterface) DetachDisk(request *ecs.DetachDiskRequest) (*ecs.DetachDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachDisk", request)
	ret0, _ := ret[0].(*ecs.DetachDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachDisk indicates an expected call of DetachDisk.
func (mr *MockECSInterfaceMockRecorder) DetachDisk(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachDisk", reflect.TypeOf((*MockECSInterface)(nil).DetachDisk), request)
}

// ResizeDisk mocks base method.
func (m *MockECSInterface) ResizeDisk(request *ecs.ResizeDiskRequest) (*ecs.ResizeDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeDisk", request)
	ret0, _ := ret[0].(*ecs.ResizeDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResizeDisk indicates an expected call of ResizeDisk.
func (mr *MockECSInterfaceMockRecorder) ResizeDisk(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeDisk", reflect.TypeOf((*MockECSInterface)(nil).ResizeDisk), request)
}

// MockECSv2Interface is a mock of ECSv2Interface interface.
type MockECSv2Interface struct {
	ctrl     *gomock.Controller
	recorder *MockECSv2InterfaceMockRecorder
}

// MockECSv2InterfaceMockRecorder is the mock recorder for MockECSv2Interface.
type MockECSv2InterfaceMockRecorder struct {
	mock *MockECSv2Interface
}

// NewMockECSv2Interface creates a new mock instance.
func NewMockECSv2Interface(ctrl *gomock.Controller) *MockECSv2Interface {
	mock := &MockECSv2Interface{ctrl: ctrl}
	mock.recorder = &MockECSv2InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockECSv2Interface) EXPECT() *MockECSv2InterfaceMockRecorder {
	return m.recorder
}

// DescribeAvailableResourceWithContext mocks base method.
func (m *MockECSv2Interface) DescribeAvailableResourceWithContext(ctx context.Context, request *client.DescribeAvailableResourceRequest, o *dara.RuntimeOptions) (*client.DescribeAvailableResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAvailableResourceWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeAvailableResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAvailableResourceWithContext indicates an expected call of DescribeAvailableResourceWithContext.
func (mr *MockECSv2InterfaceMockRecorder) DescribeAvailableResourceWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAvailableResourceWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).DescribeAvailableResourceWithContext), ctx, request, o)
}

// DescribeDisksWithContext mocks base method.
func (m *MockECSv2Interface) DescribeDisksWithContext(ctx context.Context, request *client.DescribeDisksRequest, o *dara.RuntimeOptions) (*client.DescribeDisksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDisksWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeDisksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDisksWithContext indicates an expected call of DescribeDisksWithContext.
func (mr *MockECSv2InterfaceMockRecorder) DescribeDisksWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDisksWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).DescribeDisksWithContext), ctx, request, o)
}

// DescribeInstanceTypesWithContext mocks base method.
func (m *MockECSv2Interface) DescribeInstanceTypesWithContext(ctx context.Context, request *client.DescribeInstanceTypesRequest, o *dara.RuntimeOptions) (*client.DescribeInstanceTypesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeInstanceTypesWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeInstanceTypesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstanceTypesWithContext indicates an expected call of DescribeInstanceTypesWithContext.
func (mr *MockECSv2InterfaceMockRecorder) DescribeInstanceTypesWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstanceTypesWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).DescribeInstanceTypesWithContext), ctx, request, o)
}

// DescribeInstancesWithContext mocks base method.
func (m *MockECSv2Interface) DescribeInstancesWithContext(ctx context.Context, request *client.DescribeInstancesRequest, o *dara.RuntimeOptions) (*client.DescribeInstancesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeInstancesWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeInstancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstancesWithContext indicates an expected call of DescribeInstancesWithContext.
func (mr *MockECSv2InterfaceMockRecorder) DescribeInstancesWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstancesWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).DescribeInstancesWithContext), ctx, request, o)
}

// DescribeTasksWithContext mocks base method.
func (m *MockECSv2Interface) DescribeTasksWithContext(ctx context.Context, request *client.DescribeTasksRequest, o *dara.RuntimeOptions) (*client.DescribeTasksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeTasksWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeTasksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeTasksWithContext indicates an expected call of DescribeTasksWithContext.
func (mr *MockECSv2InterfaceMockRecorder) DescribeTasksWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeTasksWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).DescribeTasksWithContext), ctx, request, o)
}

// ModifyDiskAttributeWithContext mocks base method.
func (m *MockECSv2Interface) ModifyDiskAttributeWithContext(ctx context.Context, request *client.ModifyDiskAttributeRequest, o *dara.RuntimeOptions) (*client.ModifyDiskAttributeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyDiskAttributeWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.ModifyDiskAttributeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyDiskAttributeWithContext indicates an expected call of ModifyDiskAttributeWithContext.
func (mr *MockECSv2InterfaceMockRecorder) ModifyDiskAttributeWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyDiskAttributeWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).ModifyDiskAttributeWithContext), ctx, request, o)
}

// ModifyDiskSpecWithContext mocks base method.
func (m *MockECSv2Interface) ModifyDiskSpecWithContext(ctx context.Context, request *client.ModifyDiskSpecRequest, o *dara.RuntimeOptions) (*client.ModifyDiskSpecResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyDiskSpecWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.ModifyDiskSpecResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModifyDiskSpecWithContext indicates an expected call of ModifyDiskSpecWithContext.
func (mr *MockECSv2InterfaceMockRecorder) ModifyDiskSpecWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyDiskSpecWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).ModifyDiskSpecWithContext), ctx, request, o)
}

// TagResourcesWithContext mocks base method.
func (m *MockECSv2Interface) TagResourcesWithContext(ctx context.Context, request *client.TagResourcesRequest, o *dara.RuntimeOptions) (*client.TagResourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagResourcesWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.TagResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagResourcesWithContext indicates an expected call of TagResourcesWithContext.
func (mr *MockECSv2InterfaceMockRecorder) TagResourcesWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResourcesWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).TagResourcesWithContext), ctx, request, o)
}

// UntagResourcesWithContext mocks base method.
func (m *MockECSv2Interface) UntagResourcesWithContext(ctx context.Context, request *client.UntagResourcesRequest, o *dara.RuntimeOptions) (*client.UntagResourcesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UntagResourcesWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.UntagResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UntagResourcesWithContext indicates an expected call of UntagResourcesWithContext.
func (mr *MockECSv2InterfaceMockRecorder) UntagResourcesWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntagResourcesWithContext", reflect.TypeOf((*MockECSv2Interface)(nil).UntagResourcesWithContext), ctx, request, o)
}
