// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/eflointerface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/cloud/eflointerface.go -destination=pkg/cloud/eflomock.go -package=cloud
//

// Package cloud is a generated GoMock package.
package cloud

import (
	reflect "reflect"

	client "github.com/alibabacloud-go/eflo-controller-20221215/v3/client"
	gomock "github.com/golang/mock/gomock"
)

// MockEFLOInterface is a mock of EFLOInterface interface.
type MockEFLOInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEFLOInterfaceMockRecorder
}

// MockEFLOInterfaceMockRecorder is the mock recorder for MockEFLOInterface.
type MockEFLOInterfaceMockRecorder struct {
	mock *MockEFLOInterface
}

// NewMockEFLOInterface creates a new mock instance.
func NewMockEFLOInterface(ctrl *gomock.Controller) *MockEFLOInterface {
	mock := &MockEFLOInterface{ctrl: ctrl}
	mock.recorder = &MockEFLOInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEFLOInterface) EXPECT() *MockEFLOInterfaceMockRecorder {
	return m.recorder
}

// DescribeNode mocks base method.
func (m *MockEFLOInterface) DescribeNode(request *client.DescribeNodeRequest) (*client.DescribeNodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeNode", request)
	ret0, _ := ret[0].(*client.DescribeNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeNode indicates an expected call of DescribeNode.
func (mr *MockEFLOInterfaceMockRecorder) DescribeNode(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeNode", reflect.TypeOf((*MockEFLOInterface)(nil).DescribeNode), request)
}

// DescribeNodeType mocks base method.
func (m *MockEFLOInterface) DescribeNodeType(req *client.DescribeNodeTypeRequest) (*client.DescribeNodeTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeNodeType", req)
	ret0, _ := ret[0].(*client.DescribeNodeTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeNodeType indicates an expected call of DescribeNodeType.
func (mr *MockEFLOInterfaceMockRecorder) DescribeNodeType(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeNodeType", reflect.TypeOf((*MockEFLOInterface)(nil).DescribeNodeType), req)
}
