// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/nas_interface.go

// Package cloud is a generated GoMock package.
package cloud

import (
	context "context"
	reflect "reflect"

	client "github.com/alibabacloud-go/nas-20170626/v4/client"
	dara "github.com/alibabacloud-go/tea/dara"
	gomock "github.com/golang/mock/gomock"
)

// MockNasInterface is a mock of NasInterface interface.
type MockNasInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNasInterfaceMockRecorder
}

// MockNasInterfaceMockRecorder is the mock recorder for MockNasInterface.
type MockNasInterfaceMockRecorder struct {
	mock *MockNasInterface
}

// NewMockNasInterface creates a new mock instance.
func NewMockNasInterface(ctrl *gomock.Controller) *MockNasInterface {
	mock := &MockNasInterface{ctrl: ctrl}
	mock.recorder = &MockNasInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNasInterface) EXPECT() *MockNasInterfaceMockRecorder {
	return m.recorder
}

// CancelDirQuotaWithContext mocks base method.
func (m *MockNasInterface) CancelDirQuotaWithContext(ctx context.Context, request *client.CancelDirQuotaRequest, o *dara.RuntimeOptions) (*client.CancelDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelDirQuotaWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.CancelDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelDirQuotaWithContext indicates an expected call of CancelDirQuotaWithContext.
func (mr *MockNasInterfaceMockRecorder) CancelDirQuotaWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelDirQuotaWithContext", reflect.TypeOf((*MockNasInterface)(nil).CancelDirQuotaWithContext), ctx, request, o)
}

// CreateAccessPointWithContext mocks base method.
func (m *MockNasInterface) CreateAccessPointWithContext(ctx context.Context, request *client.CreateAccessPointRequest, o *dara.RuntimeOptions) (*client.CreateAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPointWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.CreateAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPointWithContext indicates an expected call of CreateAccessPointWithContext.
func (mr *MockNasInterfaceMockRecorder) CreateAccessPointWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPointWithContext", reflect.TypeOf((*MockNasInterface)(nil).CreateAccessPointWithContext), ctx, request, o)
}

// CreateDirWithContext mocks base method.
func (m *MockNasInterface) CreateDirWithContext(ctx context.Context, request *client.CreateDirRequest, o *dara.RuntimeOptions) (*client.CreateDirResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDirWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.CreateDirResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDirWithContext indicates an expected call of CreateDirWithContext.
func (mr *MockNasInterfaceMockRecorder) CreateDirWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirWithContext", reflect.TypeOf((*MockNasInterface)(nil).CreateDirWithContext), ctx, request, o)
}

// DeleteAccessPointWithContext mocks base method.
func (m *MockNasInterface) DeleteAccessPointWithContext(ctx context.Context, request *client.DeleteAccessPointRequest, o *dara.RuntimeOptions) (*client.DeleteAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPointWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DeleteAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessPointWithContext indicates an expected call of DeleteAccessPointWithContext.
func (mr *MockNasInterfaceMockRecorder) DeleteAccessPointWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPointWithContext", reflect.TypeOf((*MockNasInterface)(nil).DeleteAccessPointWithContext), ctx, request, o)
}

// DescribeAccessPointWithContext mocks base method.
func (m *MockNasInterface) DescribeAccessPointWithContext(ctx context.Context, request *client.DescribeAccessPointRequest, o *dara.RuntimeOptions) (*client.DescribeAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAccessPointWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAccessPointWithContext indicates an expected call of DescribeAccessPointWithContext.
func (mr *MockNasInterfaceMockRecorder) DescribeAccessPointWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAccessPointWithContext", reflect.TypeOf((*MockNasInterface)(nil).DescribeAccessPointWithContext), ctx, request, o)
}

// DescribeFileSystemsWithContext mocks base method.
func (m *MockNasInterface) DescribeFileSystemsWithContext(ctx context.Context, request *client.DescribeFileSystemsRequest, o *dara.RuntimeOptions) (*client.DescribeFileSystemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFileSystemsWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.DescribeFileSystemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFileSystemsWithContext indicates an expected call of DescribeFileSystemsWithContext.
func (mr *MockNasInterfaceMockRecorder) DescribeFileSystemsWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFileSystemsWithContext", reflect.TypeOf((*MockNasInterface)(nil).DescribeFileSystemsWithContext), ctx, request, o)
}

// GetRecycleBinAttributeWithContext mocks base method.
func (m *MockNasInterface) GetRecycleBinAttributeWithContext(ctx context.Context, request *client.GetRecycleBinAttributeRequest, o *dara.RuntimeOptions) (*client.GetRecycleBinAttributeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecycleBinAttributeWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.GetRecycleBinAttributeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecycleBinAttributeWithContext indicates an expected call of GetRecycleBinAttributeWithContext.
func (mr *MockNasInterfaceMockRecorder) GetRecycleBinAttributeWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecycleBinAttributeWithContext", reflect.TypeOf((*MockNasInterface)(nil).GetRecycleBinAttributeWithContext), ctx, request, o)
}

// SetDirQuotaWithContext mocks base method.
func (m *MockNasInterface) SetDirQuotaWithContext(ctx context.Context, request *client.SetDirQuotaRequest, o *dara.RuntimeOptions) (*client.SetDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDirQuotaWithContext", ctx, request, o)
	ret0, _ := ret[0].(*client.SetDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDirQuotaWithContext indicates an expected call of SetDirQuotaWithContext.
func (mr *MockNasInterfaceMockRecorder) SetDirQuotaWithContext(ctx, request, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDirQuotaWithContext", reflect.TypeOf((*MockNasInterface)(nil).SetDirQuotaWithContext), ctx, request, o)
}
