// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/nas_interface.go

// Package cloud is a generated GoMock package.
package cloud

import (
	context "context"
	reflect "reflect"

	client "github.com/alibabacloud-go/nas-20170626/v4/client"
	dara "github.com/alibabacloud-go/tea/dara"
	gomock "github.com/golang/mock/gomock"
)

// MockNasInterface is a mock of NasInterface interface.
type MockNasInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNasInterfaceMockRecorder
}

// MockNasInterfaceMockRecorder is the mock recorder for MockNasInterface.
type MockNasInterfaceMockRecorder struct {
	mock *MockNasInterface
}

// NewMockNasInterface creates a new mock instance.
func NewMockNasInterface(ctrl *gomock.Controller) *MockNasInterface {
	mock := &MockNasInterface{ctrl: ctrl}
	mock.recorder = &MockNasInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNasInterface) EXPECT() *MockNasInterfaceMockRecorder {
	return m.recorder
}

// CancelDirQuota mocks base method.
func (m *MockNasInterface) CancelDirQuota(request *client.CancelDirQuotaRequest) (*client.CancelDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelDirQuota", request)
	ret0, _ := ret[0].(*client.CancelDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelDirQuota indicates an expected call of CancelDirQuota.
func (mr *MockNasInterfaceMockRecorder) CancelDirQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelDirQuota", reflect.TypeOf((*MockNasInterface)(nil).CancelDirQuota), request)
}

// CreateAccessPoint mocks base method.
func (m *MockNasInterface) CreateAccessPoint(request *client.CreateAccessPointRequest) (*client.CreateAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPoint", request)
	ret0, _ := ret[0].(*client.CreateAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPoint indicates an expected call of CreateAccessPoint.
func (mr *MockNasInterfaceMockRecorder) CreateAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPoint", reflect.TypeOf((*MockNasInterface)(nil).CreateAccessPoint), request)
}

// CreateAgenticSpace mocks base method.
func (m *MockNasInterface) CreateAgenticSpace(request *client.CreateAgenticSpaceRequest) (*client.CreateAgenticSpaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgenticSpace", request)
	ret0, _ := ret[0].(*client.CreateAgenticSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgenticSpace indicates an expected call of CreateAgenticSpace.
func (mr *MockNasInterfaceMockRecorder) CreateAgenticSpace(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgenticSpace", reflect.TypeOf((*MockNasInterface)(nil).CreateAgenticSpace), request)
}

// CreateDir mocks base method.
func (m *MockNasInterface) CreateDir(request *client.CreateDirRequest) (*client.CreateDirResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDir", request)
	ret0, _ := ret[0].(*client.CreateDirResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDir indicates an expected call of CreateDir.
func (mr *MockNasInterfaceMockRecorder) CreateDir(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDir", reflect.TypeOf((*MockNasInterface)(nil).CreateDir), request)
}

// DeleteAccessPointWithContext mocks base method.
func (m *MockNasInterface) DeleteAccessPointWithContext(ctx context.Context, request *client.DeleteAccessPointRequest, runtime *dara.RuntimeOptions) (*client.DeleteAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPointWithContext", ctx, request, runtime)
	ret0, _ := ret[0].(*client.DeleteAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessPointWithContext indicates an expected call of DeleteAccessPointWithContext.
func (mr *MockNasInterfaceMockRecorder) DeleteAccessPointWithContext(ctx, request, runtime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPointWithContext", reflect.TypeOf((*MockNasInterface)(nil).DeleteAccessPointWithContext), ctx, request, runtime)
}

// DeleteAgenticSpace mocks base method.
func (m *MockNasInterface) DeleteAgenticSpace(request *client.DeleteAgenticSpaceRequest) (*client.DeleteAgenticSpaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgenticSpace", request)
	ret0, _ := ret[0].(*client.DeleteAgenticSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAgenticSpace indicates an expected call of DeleteAgenticSpace.
func (mr *MockNasInterfaceMockRecorder) DeleteAgenticSpace(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgenticSpace", reflect.TypeOf((*MockNasInterface)(nil).DeleteAgenticSpace), request)
}

// DescribeAccessPoint mocks base method.
func (m *MockNasInterface) DescribeAccessPoint(request *client.DescribeAccessPointRequest) (*client.DescribeAccessPointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAccessPoint", request)
	ret0, _ := ret[0].(*client.DescribeAccessPointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAccessPoint indicates an expected call of DescribeAccessPoint.
func (mr *MockNasInterfaceMockRecorder) DescribeAccessPoint(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAccessPoint", reflect.TypeOf((*MockNasInterface)(nil).DescribeAccessPoint), request)
}

// DescribeAgenticSpacesWithContext mocks base method.
func (m *MockNasInterface) DescribeAgenticSpacesWithContext(ctx context.Context, request *client.DescribeAgenticSpacesRequest, runtime *dara.RuntimeOptions) (*client.DescribeAgenticSpacesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAgenticSpacesWithContext", ctx, request, runtime)
	ret0, _ := ret[0].(*client.DescribeAgenticSpacesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAgenticSpacesWithContext indicates an expected call of DescribeAgenticSpacesWithContext.
func (mr *MockNasInterfaceMockRecorder) DescribeAgenticSpacesWithContext(ctx, request, runtime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAgenticSpacesWithContext", reflect.TypeOf((*MockNasInterface)(nil).DescribeAgenticSpacesWithContext), ctx, request, runtime)
}

// DescribeFileSystems mocks base method.
func (m *MockNasInterface) DescribeFileSystems(request *client.DescribeFileSystemsRequest) (*client.DescribeFileSystemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFileSystems", request)
	ret0, _ := ret[0].(*client.DescribeFileSystemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFileSystems indicates an expected call of DescribeFileSystems.
func (mr *MockNasInterfaceMockRecorder) DescribeFileSystems(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFileSystems", reflect.TypeOf((*MockNasInterface)(nil).DescribeFileSystems), request)
}

// GetAgenticSpace mocks base method.
func (m *MockNasInterface) GetAgenticSpace(request *client.GetAgenticSpaceRequest) (*client.GetAgenticSpaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgenticSpace", request)
	ret0, _ := ret[0].(*client.GetAgenticSpaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgenticSpace indicates an expected call of GetAgenticSpace.
func (mr *MockNasInterfaceMockRecorder) GetAgenticSpace(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgenticSpace", reflect.TypeOf((*MockNasInterface)(nil).GetAgenticSpace), request)
}

// GetRecycleBinAttribute mocks base method.
func (m *MockNasInterface) GetRecycleBinAttribute(request *client.GetRecycleBinAttributeRequest) (*client.GetRecycleBinAttributeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecycleBinAttribute", request)
	ret0, _ := ret[0].(*client.GetRecycleBinAttributeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecycleBinAttribute indicates an expected call of GetRecycleBinAttribute.
func (mr *MockNasInterfaceMockRecorder) GetRecycleBinAttribute(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecycleBinAttribute", reflect.TypeOf((*MockNasInterface)(nil).GetRecycleBinAttribute), request)
}

// ListAccessPoints mocks base method.
func (m *MockNasInterface) ListAccessPoints(request *client.ListAccessPointsRequest) (*client.ListAccessPointsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessPoints", request)
	ret0, _ := ret[0].(*client.ListAccessPointsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessPoints indicates an expected call of ListAccessPoints.
func (mr *MockNasInterfaceMockRecorder) ListAccessPoints(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPoints", reflect.TypeOf((*MockNasInterface)(nil).ListAccessPoints), request)
}

// SetAgenticSpaceQuota mocks base method.
func (m *MockNasInterface) SetAgenticSpaceQuota(request *client.SetAgenticSpaceQuotaRequest) (*client.SetAgenticSpaceQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAgenticSpaceQuota", request)
	ret0, _ := ret[0].(*client.SetAgenticSpaceQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAgenticSpaceQuota indicates an expected call of SetAgenticSpaceQuota.
func (mr *MockNasInterfaceMockRecorder) SetAgenticSpaceQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgenticSpaceQuota", reflect.TypeOf((*MockNasInterface)(nil).SetAgenticSpaceQuota), request)
}

// SetDirQuota mocks base method.
func (m *MockNasInterface) SetDirQuota(request *client.SetDirQuotaRequest) (*client.SetDirQuotaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDirQuota", request)
	ret0, _ := ret[0].(*client.SetDirQuotaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDirQuota indicates an expected call of SetDirQuota.
func (mr *MockNasInterfaceMockRecorder) SetDirQuota(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDirQuota", reflect.TypeOf((*MockNasInterface)(nil).SetDirQuota), request)
}
