// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/stsinterface.go

// Package mock_cloud is a generated GoMock package.
package cloud

import (
	reflect "reflect"

	sts "github.com/aliyun/alibaba-cloud-sdk-go/services/sts"
	gomock "github.com/golang/mock/gomock"
)

// MockSTSInterface is a mock of STSInterface interface.
type MockSTSInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSTSInterfaceMockRecorder
}

// MockSTSInterfaceMockRecorder is the mock recorder for MockSTSInterface.
type MockSTSInterfaceMockRecorder struct {
	mock *MockSTSInterface
}

// NewMockSTSInterface creates a new mock instance.
func NewMockSTSInterface(ctrl *gomock.Controller) *MockSTSInterface {
	mock := &MockSTSInterface{ctrl: ctrl}
	mock.recorder = &MockSTSInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSTSInterface) EXPECT() *MockSTSInterfaceMockRecorder {
	return m.recorder
}

// GetCallerIdentity mocks base method.
func (m *MockSTSInterface) GetCallerIdentity(request *sts.GetCallerIdentityRequest) (*sts.GetCallerIdentityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallerIdentity", request)
	ret0, _ := ret[0].(*sts.GetCallerIdentityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallerIdentity indicates an expected call of GetCallerIdentity.
func (mr *MockSTSInterfaceMockRecorder) GetCallerIdentity(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallerIdentity", reflect.TypeOf((*MockSTSInterface)(nil).GetCallerIdentity), request)
}
