// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloud/stsinterface.go

// Package cloud is a generated GoMock package.
package cloud

import (
	reflect "reflect"

	client "github.com/alibabacloud-go/sts-20150401/v2/client"
	gomock "github.com/golang/mock/gomock"
)

// MockSTSInterface is a mock of STSInterface interface.
type MockSTSInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSTSInterfaceMockRecorder
}

// MockSTSInterfaceMockRecorder is the mock recorder for MockSTSInterface.
type MockSTSInterfaceMockRecorder struct {
	mock *MockSTSInterface
}

// NewMockSTSInterface creates a new mock instance.
func NewMockSTSInterface(ctrl *gomock.Controller) *MockSTSInterface {
	mock := &MockSTSInterface{ctrl: ctrl}
	mock.recorder = &MockSTSInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSTSInterface) EXPECT() *MockSTSInterfaceMockRecorder {
	return m.recorder
}

// AssumeRoleWithOIDC mocks base method.
func (m *MockSTSInterface) AssumeRoleWithOIDC(request *client.AssumeRoleWithOIDCRequest) (*client.AssumeRoleWithOIDCResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssumeRoleWithOIDC", request)
	ret0, _ := ret[0].(*client.AssumeRoleWithOIDCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssumeRoleWithOIDC indicates an expected call of AssumeRoleWithOIDC.
func (mr *MockSTSInterfaceMockRecorder) AssumeRoleWithOIDC(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssumeRoleWithOIDC", reflect.TypeOf((*MockSTSInterface)(nil).AssumeRoleWithOIDC), request)
}

// GetCallerIdentity mocks base method.
func (m *MockSTSInterface) GetCallerIdentity() (*client.GetCallerIdentityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallerIdentity")
	ret0, _ := ret[0].(*client.GetCallerIdentityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCallerIdentity indicates an expected call of GetCallerIdentity.
func (mr *MockSTSInterfaceMockRecorder) GetCallerIdentity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallerIdentity", reflect.TypeOf((*MockSTSInterface)(nil).GetCallerIdentity))
}
