apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mem
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mem-pvc
            mountPath: "/data"
      volumes:
        - name: mem-pvc
          persistentVolumeClaim:
            claimName: mem-pvc
