apiVersion: v1
kind: PersistentVolume
metadata:
  name: mem-csi-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: memplugin.csi.alibabacloud.com
    volumeHandle: mem-csi-pv