kind: Service
apiVersion: v1
metadata:
  name: csi-nas-attacher
  labels:
    app: csi-nas-attacher
spec:
  selector:
    app: csi-nas-attacher
  ports:
  - name: dummy
    port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-nas-attacher
spec:
  serviceName: "csi-nas-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-nas-attacher
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccount: alicloud-csi-plugin
      containers:
      - name: csi-attacher
        image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-attacher:v1.0.0
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /socketDir/csi.sock
        imagePullPolicy: "Always"
        volumeMounts:
        - name: socket-dir
          mountPath: /socketDir
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/nasplugin.csi.alibabacloud.com
          type: DirectoryOrCreate