apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: alicloud-disk-multizone
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    zoneId: cn-beijing-a,cn-beijing-b,cn-beijing-c
    regionId: cn-beijing
    type: cloud_ssd
reclaimPolicy: Retain