apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-pv
  labels:
    alicloud-pvname: static-disk-pv-options
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nodiratime
  - barrier=0
  csi:
    driver: diskplugin.csi.alibabacloud.com
    volumeHandle: d-2ze4tf94z3fkeg6ttv52
    volumeAttributes:
      mkfsOptions: "-q -L yunpan -J size=2048 -T largefile"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.diskplugin.csi.alibabacloud.com/zone
          operator: In
          values:
          - cn-hangzhou-a