name: Release Charts

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - deploy/charts/**/Chart.yaml

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a0d2dc62c5e491af8ef6ba64a2e02bcf3fb33aa1 # v1.7.0
        with:
          charts_dir: deploy/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
