name: Typos GitHub Action
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Check spelling
      uses: crate-ci/typos@aca895bf05aec0cb7dffa6f94495e923224d9f17 # v1.46.2
      with:
        files: ./
        config: ./_typos.toml
